--IP Functional Simulation Model
--VERSION_BEGIN 11.1SP2 cbx_mgl 2012:01:25:21:15:41:SJ cbx_simgen 2012:01:25:21:13:53:SJ  VERSION_END


-- Copyright (C) 1991-2011 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- You may only use these simulation model output files for simulation
-- purposes and expressly not for synthesis or any other purposes (in which
-- event Altera disclaims all warranties of any kind).


--synopsys translate_off

 LIBRARY sgate;
 USE sgate.sgate_pack.all;

--synthesis_resources = lut 37 mux21 7 oper_add 1 oper_less_than 2 
 LIBRARY ieee;
 USE ieee.std_logic_1164.all;

 ENTITY  Nios1_nios2_qsys_jtag_debug_module_translator IS 
	 PORT 
	 ( 
		 av_address	:	OUT  STD_LOGIC_VECTOR (8 DOWNTO 0);
		 av_begintransfer	:	OUT  STD_LOGIC;
		 av_byteenable	:	OUT  STD_LOGIC_VECTOR (3 DOWNTO 0);
		 av_chipselect	:	OUT  STD_LOGIC;
		 av_debugaccess	:	OUT  STD_LOGIC;
		 av_readdata	:	IN  STD_LOGIC_VECTOR (31 DOWNTO 0);
		 av_write	:	OUT  STD_LOGIC;
		 av_writedata	:	OUT  STD_LOGIC_VECTOR (31 DOWNTO 0);
		 clk	:	IN  STD_LOGIC;
		 reset	:	IN  STD_LOGIC;
		 uav_address	:	IN  STD_LOGIC_VECTOR (18 DOWNTO 0);
		 uav_burstcount	:	IN  STD_LOGIC_VECTOR (2 DOWNTO 0);
		 uav_byteenable	:	IN  STD_LOGIC_VECTOR (3 DOWNTO 0);
		 uav_debugaccess	:	IN  STD_LOGIC;
		 uav_lock	:	IN  STD_LOGIC;
		 uav_read	:	IN  STD_LOGIC;
		 uav_readdata	:	OUT  STD_LOGIC_VECTOR (31 DOWNTO 0);
		 uav_readdatavalid	:	OUT  STD_LOGIC;
		 uav_waitrequest	:	OUT  STD_LOGIC;
		 uav_write	:	IN  STD_LOGIC;
		 uav_writedata	:	IN  STD_LOGIC_VECTOR (31 DOWNTO 0)
	 ); 
 END Nios1_nios2_qsys_jtag_debug_module_translator;

 ARCHITECTURE RTL OF Nios1_nios2_qsys_jtag_debug_module_translator IS

	 ATTRIBUTE synthesis_clearbox : natural;
	 ATTRIBUTE synthesis_clearbox OF RTL : ARCHITECTURE IS 1;
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_waitrequest_reset_override_204q	:	STD_LOGIC := '0';
	 SIGNAL  wire_nl_w239w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_0_240q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_10_226q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_11_225q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_12_224q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_13_223q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_14_222q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_15_221q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_16_220q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_17_219q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_18_218q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_19_217q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_1_235q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_20_216q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_21_215q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_22_214q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_23_213q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_24_212q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_25_211q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_26_210q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_27_209q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_28_208q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_29_207q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_2_234q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_30_206q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_31_205q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_3_233q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_4_232q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_5_231q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_6_230q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_7_229q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_8_228q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_9_227q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_end_begintransfer_265q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_read_latency_shift_reg_0_243q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_0_192q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_1_191q	:	STD_LOGIC := '0';
	 SIGNAL  wire_nO_w243w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_nO_w203w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_nO_w200w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_waitrequest_generated_202m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_end_begintransfer_250m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_end_begintransfer_251m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_186m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_187m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_189m_dataout	:	STD_LOGIC;
	 SIGNAL	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_190m_dataout	:	STD_LOGIC;
	 SIGNAL  wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_add0_185_a	:	STD_LOGIC_VECTOR (1 DOWNTO 0);
	 SIGNAL  wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_add0_185_b	:	STD_LOGIC_VECTOR (1 DOWNTO 0);
	 SIGNAL  wire_gnd	:	STD_LOGIC;
	 SIGNAL  wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_add0_185_o	:	STD_LOGIC_VECTOR (1 DOWNTO 0);
	 SIGNAL  wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan0_194_a	:	STD_LOGIC_VECTOR (1 DOWNTO 0);
	 SIGNAL  wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan0_194_b	:	STD_LOGIC_VECTOR (1 DOWNTO 0);
	 SIGNAL  wire_vcc	:	STD_LOGIC;
	 SIGNAL  wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan0_194_o	:	STD_LOGIC;
	 SIGNAL  wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan1_196_a	:	STD_LOGIC_VECTOR (1 DOWNTO 0);
	 SIGNAL  wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan1_196_b	:	STD_LOGIC_VECTOR (1 DOWNTO 0);
	 SIGNAL  wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan1_196_o	:	STD_LOGIC;
	 SIGNAL  wire_w_lg_reset183w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w181w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  s_wire_gnd :	STD_LOGIC;
	 SIGNAL  s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_always7_188_dataout :	STD_LOGIC;
	 SIGNAL  s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_begintransfer_245_dataout :	STD_LOGIC;
	 SIGNAL  s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_begintransfer_247_dataout :	STD_LOGIC;
	 SIGNAL  s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_uav_waitrequest_203_dataout :	STD_LOGIC;
	 SIGNAL  s_wire_vcc :	STD_LOGIC;
 BEGIN

	wire_gnd <= '0';
	wire_vcc <= '1';
	wire_w_lg_reset183w(0) <= NOT reset;
	wire_w181w(0) <= NOT s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_uav_waitrequest_203_dataout;
	av_address <= ( uav_address(10 DOWNTO 2));
	av_begintransfer <= s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_begintransfer_247_dataout;
	av_byteenable <= ( uav_byteenable(3 DOWNTO 0));
	av_chipselect <= s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_begintransfer_245_dataout;
	av_debugaccess <= uav_debugaccess;
	av_write <= ((uav_write AND wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan0_194_o) AND wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan1_196_o);
	av_writedata <= ( uav_writedata(31 DOWNTO 0));
	s_wire_gnd <= '0';
	s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_always7_188_dataout <= (wire_w181w(0) OR nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_waitrequest_reset_override_204q);
	s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_begintransfer_245_dataout <= (uav_read OR uav_write);
	s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_begintransfer_247_dataout <= (s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_begintransfer_245_dataout AND wire_nO_w243w(0));
	s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_uav_waitrequest_203_dataout <= (wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_waitrequest_generated_202m_dataout OR nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_waitrequest_reset_override_204q);
	s_wire_vcc <= '1';
	uav_readdata <= ( nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_31_205q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_30_206q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_29_207q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_28_208q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_27_209q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_26_210q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_25_211q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_24_212q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_23_213q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_22_214q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_21_215q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_20_216q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_19_217q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_18_218q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_17_219q
 & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_16_220q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_15_221q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_14_222q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_13_223q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_12_224q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_11_225q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_10_226q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_9_227q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_8_228q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_7_229q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_6_230q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_5_231q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_4_232q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_3_233q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_2_234q
 & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_1_235q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_0_240q);
	uav_readdatavalid <= nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_read_latency_shift_reg_0_243q;
	uav_waitrequest <= s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_uav_waitrequest_203_dataout;
	PROCESS (clk, reset)
	BEGIN
		IF (reset = '1') THEN
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_waitrequest_reset_override_204q <= '1';
		ELSIF (clk = '1' AND clk'event) THEN
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_waitrequest_reset_override_204q <= s_wire_gnd;
		END IF;
		if (now = 0 ns) then
			nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_waitrequest_reset_override_204q <= '1' after 1 ps;
		end if;
	END PROCESS;
	wire_nl_w239w(0) <= NOT nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_waitrequest_reset_override_204q;
	PROCESS (clk, reset)
	BEGIN
		IF (reset = '1') THEN
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_0_240q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_10_226q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_11_225q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_12_224q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_13_223q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_14_222q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_15_221q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_16_220q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_17_219q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_18_218q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_19_217q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_1_235q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_20_216q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_21_215q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_22_214q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_23_213q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_24_212q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_25_211q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_26_210q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_27_209q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_28_208q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_29_207q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_2_234q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_30_206q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_31_205q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_3_233q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_4_232q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_5_231q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_6_230q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_7_229q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_8_228q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_9_227q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_end_begintransfer_265q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_read_latency_shift_reg_0_243q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_0_192q <= '0';
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_1_191q <= '0';
		ELSIF (clk = '1' AND clk'event) THEN
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_0_240q <= av_readdata(0);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_10_226q <= av_readdata(10);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_11_225q <= av_readdata(11);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_12_224q <= av_readdata(12);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_13_223q <= av_readdata(13);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_14_222q <= av_readdata(14);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_15_221q <= av_readdata(15);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_16_220q <= av_readdata(16);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_17_219q <= av_readdata(17);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_18_218q <= av_readdata(18);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_19_217q <= av_readdata(19);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_1_235q <= av_readdata(1);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_20_216q <= av_readdata(20);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_21_215q <= av_readdata(21);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_22_214q <= av_readdata(22);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_23_213q <= av_readdata(23);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_24_212q <= av_readdata(24);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_25_211q <= av_readdata(25);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_26_210q <= av_readdata(26);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_27_209q <= av_readdata(27);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_28_208q <= av_readdata(28);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_29_207q <= av_readdata(29);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_2_234q <= av_readdata(2);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_30_206q <= av_readdata(30);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_31_205q <= av_readdata(31);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_3_233q <= av_readdata(3);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_4_232q <= av_readdata(4);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_5_231q <= av_readdata(5);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_6_230q <= av_readdata(6);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_7_229q <= av_readdata(7);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_8_228q <= av_readdata(8);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_readdata_pre_9_227q <= av_readdata(9);
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_end_begintransfer_265q <= wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_end_begintransfer_251m_dataout;
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_read_latency_shift_reg_0_243q <= (uav_read AND (wire_w181w(0) AND wire_nl_w239w(0)));
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_0_192q <= wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_190m_dataout;
				nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_1_191q <= wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_189m_dataout;
		END IF;
	END PROCESS;
	wire_nO_w243w(0) <= NOT nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_end_begintransfer_265q;
	wire_nO_w203w(0) <= NOT nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_0_192q;
	wire_nO_w200w(0) <= NOT nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_1_191q;
	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_waitrequest_generated_202m_dataout <= (NOT (wire_nO_w200w(0) AND wire_nO_w203w(0))) WHEN uav_write = '1'  ELSE (NOT (wire_nO_w200w(0) AND nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_0_192q));
	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_end_begintransfer_250m_dataout <= nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_end_begintransfer_265q AND s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_uav_waitrequest_203_dataout;
	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_end_begintransfer_251m_dataout <= wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_end_begintransfer_250m_dataout OR (wire_nl_w239w(0) AND (s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_uav_waitrequest_203_dataout AND s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_begintransfer_247_dataout));
	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_186m_dataout <= wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_add0_185_o(1) AND s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_begintransfer_245_dataout;
	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_187m_dataout <= wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_add0_185_o(0) AND s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_av_begintransfer_245_dataout;
	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_189m_dataout <= wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_186m_dataout AND NOT(s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_always7_188_dataout);
	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_190m_dataout <= wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_187m_dataout AND NOT(s_wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_always7_188_dataout);
	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_add0_185_a <= ( nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_1_191q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_0_192q);
	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_add0_185_b <= ( "0" & "1");
	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_add0_185 :  oper_add
	  GENERIC MAP (
		sgate_representation => 0,
		width_a => 2,
		width_b => 2,
		width_o => 2
	  )
	  PORT MAP ( 
		a => wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_add0_185_a,
		b => wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_add0_185_b,
		cin => wire_gnd,
		o => wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_add0_185_o
	  );
	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan0_194_a <= ( "0" & "0");
	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan0_194_b <= ( nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_1_191q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_0_192q);
	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan0_194 :  oper_less_than
	  GENERIC MAP (
		sgate_representation => 0,
		width_a => 2,
		width_b => 2
	  )
	  PORT MAP ( 
		a => wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan0_194_a,
		b => wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan0_194_b,
		cin => wire_vcc,
		o => wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan0_194_o
	  );
	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan1_196_a <= ( nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_1_191q & nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_wait_latency_counter_0_192q);
	wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan1_196_b <= ( "0" & "0");
	nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan1_196 :  oper_less_than
	  GENERIC MAP (
		sgate_representation => 0,
		width_a => 2,
		width_b => 2
	  )
	  PORT MAP ( 
		a => wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan1_196_a,
		b => wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan1_196_b,
		cin => wire_vcc,
		o => wire_nios1_nios2_qsys_jtag_debug_module_translator_altera_merlin_slave_translator_nios2_qsys_jtag_debug_module_translator_lessthan1_196_o
	  );

 END RTL; --Nios1_nios2_qsys_jtag_debug_module_translator
--synopsys translate_on
--VALID FILE
