add wave -noupdate -divider {Nios1_nios2_qsys: top-level ports}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/i_readdata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/i_readdatavalid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/i_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/i_address
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/i_read
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/clk
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/reset_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/d_readdata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/d_waitrequest
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/d_address
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/d_byteenable
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/d_read
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/d_write
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/d_writedata
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/d_irq
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/d_readdatavalid
add wave -noupdate -divider {Nios1_nios2_qsys: base pipeline}
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/clk
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/reset_n
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/D_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/F_pcb_nxt
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/F_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/D_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/E_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/M_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_pcb
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/W_pcb
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Nios1_nios2_qsys/F_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Nios1_nios2_qsys/D_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Nios1_nios2_qsys/E_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Nios1_nios2_qsys/M_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Nios1_nios2_qsys/A_vinst
add wave -noupdate -format Logic -radix ascii /test_bench/DUT/the_Nios1_nios2_qsys/W_vinst
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/F_inst_ram_hit
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/F_iw_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/F_issue
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/F_kill
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/D_kill
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/D_refetch
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/D_issue
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/D_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/D_rdprs_stall
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/D_rdprs_stall_done
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/E_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/M_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/W_valid
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/W_wr_dst_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/W_dst_regnum
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/W_wr_data
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/D_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/E_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/M_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_en
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/F_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/D_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/E_iw
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/M_pipe_flush
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/M_pipe_flush_baddr
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/norm_intr_req
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_status_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_status_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_estatus_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_estatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_bstatus_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_bstatus_reg_pie
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_ienable_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_ienable_reg_irq1
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_ienable_reg_irq2
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_ienable_reg_irq3
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_ienable_reg_irq5
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_ienable_reg_irq8
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_ipending_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_ipending_reg_irq1
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_ipending_reg_irq2
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_ipending_reg_irq3
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_ipending_reg_irq5
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_ipending_reg_irq8
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/A_cpuid_reg
add wave -noupdate -format Logic -radix hexadecimal /test_bench/DUT/the_Nios1_nios2_qsys/E_valid_prior_to_hbreak

configure wave -justifyvalue right
configure wave -signalnamewidth 1
TreeUpdate [SetDefaultTree]
