--IP Functional Simulation Model
--VERSION_BEGIN 11.1SP2 cbx_mgl 2012:01:25:21:15:41:SJ cbx_simgen 2012:01:25:21:13:53:SJ  VERSION_END


-- Copyright (C) 1991-2011 Altera Corporation
-- Your use of Altera Corporation's design tools, logic functions 
-- and other software and tools, and its AMPP partner logic 
-- functions, and any output files from any of the foregoing 
-- (including device programming or simulation files), and any 
-- associated documentation or information are expressly subject 
-- to the terms and conditions of the Altera Program License 
-- Subscription Agreement, Altera MegaCore Function License 
-- Agreement, or other applicable license agreement, including, 
-- without limitation, that your use is for the sole purpose of 
-- programming logic devices manufactured by Altera and sold by 
-- Altera or its authorized distributors.  Please refer to the 
-- applicable agreement for further details.

-- You may only use these simulation model output files for simulation
-- purposes and expressly not for synthesis or any other purposes (in which
-- event Altera disclaims all warranties of any kind).


--synopsys translate_off

--synthesis_resources = lut 34 
 LIBRARY ieee;
 USE ieee.std_logic_1164.all;

 ENTITY  Nios1_jtag_uart_avalon_jtag_slave_translator IS 
	 PORT 
	 ( 
		 av_address	:	OUT  STD_LOGIC;
		 av_chipselect	:	OUT  STD_LOGIC;
		 av_read	:	OUT  STD_LOGIC;
		 av_readdata	:	IN  STD_LOGIC_VECTOR (31 DOWNTO 0);
		 av_waitrequest	:	IN  STD_LOGIC;
		 av_write	:	OUT  STD_LOGIC;
		 av_writedata	:	OUT  STD_LOGIC_VECTOR (31 DOWNTO 0);
		 clk	:	IN  STD_LOGIC;
		 reset	:	IN  STD_LOGIC;
		 uav_address	:	IN  STD_LOGIC_VECTOR (18 DOWNTO 0);
		 uav_burstcount	:	IN  STD_LOGIC_VECTOR (2 DOWNTO 0);
		 uav_byteenable	:	IN  STD_LOGIC_VECTOR (3 DOWNTO 0);
		 uav_debugaccess	:	IN  STD_LOGIC;
		 uav_lock	:	IN  STD_LOGIC;
		 uav_read	:	IN  STD_LOGIC;
		 uav_readdata	:	OUT  STD_LOGIC_VECTOR (31 DOWNTO 0);
		 uav_readdatavalid	:	OUT  STD_LOGIC;
		 uav_waitrequest	:	OUT  STD_LOGIC;
		 uav_write	:	IN  STD_LOGIC;
		 uav_writedata	:	IN  STD_LOGIC_VECTOR (31 DOWNTO 0)
	 ); 
 END Nios1_jtag_uart_avalon_jtag_slave_translator;

 ARCHITECTURE RTL OF Nios1_jtag_uart_avalon_jtag_slave_translator IS

	 ATTRIBUTE synthesis_clearbox : natural;
	 ATTRIBUTE synthesis_clearbox OF RTL : ARCHITECTURE IS 1;
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_0_206q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_10_192q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_11_191q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_12_190q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_13_189q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_14_188q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_15_187q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_16_186q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_17_185q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_18_184q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_19_183q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_1_201q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_20_182q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_21_181q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_22_180q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_23_179q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_24_178q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_25_177q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_26_176q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_27_175q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_28_174q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_29_173q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_2_200q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_30_172q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_31_171q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_3_199q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_4_198q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_5_197q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_6_196q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_7_195q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_8_194q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_9_193q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_read_latency_shift_reg_0_209q	:	STD_LOGIC := '0';
	 SIGNAL	nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_waitrequest_reset_override_170q	:	STD_LOGIC := '0';
	 SIGNAL  wire_nO_w166w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_av_waitrequest165w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  wire_w_lg_reset132w	:	STD_LOGIC_VECTOR (0 DOWNTO 0);
	 SIGNAL  s_wire_gnd :	STD_LOGIC;
	 SIGNAL  s_wire_vcc :	STD_LOGIC;
 BEGIN

	wire_w_lg_av_waitrequest165w(0) <= NOT av_waitrequest;
	wire_w_lg_reset132w(0) <= NOT reset;
	av_address <= uav_address(2);
	av_chipselect <= (uav_read OR uav_write);
	av_read <= uav_read;
	av_write <= uav_write;
	av_writedata <= ( uav_writedata(31 DOWNTO 0));
	s_wire_gnd <= '0';
	s_wire_vcc <= '1';
	uav_readdata <= ( nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_31_171q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_30_172q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_29_173q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_28_174q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_27_175q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_26_176q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_25_177q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_24_178q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_23_179q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_22_180q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_21_181q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_20_182q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_19_183q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_18_184q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_17_185q
 & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_16_186q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_15_187q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_14_188q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_13_189q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_12_190q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_11_191q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_10_192q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_9_193q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_8_194q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_7_195q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_6_196q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_5_197q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_4_198q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_3_199q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_2_200q
 & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_1_201q & nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_0_206q);
	uav_readdatavalid <= nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_read_latency_shift_reg_0_209q;
	uav_waitrequest <= av_waitrequest;
	PROCESS (clk, reset)
	BEGIN
		IF (reset = '1') THEN
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_0_206q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_10_192q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_11_191q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_12_190q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_13_189q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_14_188q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_15_187q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_16_186q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_17_185q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_18_184q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_19_183q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_1_201q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_20_182q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_21_181q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_22_180q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_23_179q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_24_178q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_25_177q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_26_176q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_27_175q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_28_174q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_29_173q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_2_200q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_30_172q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_31_171q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_3_199q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_4_198q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_5_197q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_6_196q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_7_195q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_8_194q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_9_193q <= '0';
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_read_latency_shift_reg_0_209q <= '0';
		ELSIF (clk = '1' AND clk'event) THEN
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_0_206q <= av_readdata(0);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_10_192q <= av_readdata(10);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_11_191q <= av_readdata(11);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_12_190q <= av_readdata(12);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_13_189q <= av_readdata(13);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_14_188q <= av_readdata(14);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_15_187q <= av_readdata(15);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_16_186q <= av_readdata(16);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_17_185q <= av_readdata(17);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_18_184q <= av_readdata(18);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_19_183q <= av_readdata(19);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_1_201q <= av_readdata(1);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_20_182q <= av_readdata(20);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_21_181q <= av_readdata(21);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_22_180q <= av_readdata(22);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_23_179q <= av_readdata(23);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_24_178q <= av_readdata(24);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_25_177q <= av_readdata(25);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_26_176q <= av_readdata(26);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_27_175q <= av_readdata(27);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_28_174q <= av_readdata(28);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_29_173q <= av_readdata(29);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_2_200q <= av_readdata(2);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_30_172q <= av_readdata(30);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_31_171q <= av_readdata(31);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_3_199q <= av_readdata(3);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_4_198q <= av_readdata(4);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_5_197q <= av_readdata(5);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_6_196q <= av_readdata(6);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_7_195q <= av_readdata(7);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_8_194q <= av_readdata(8);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_av_readdata_pre_9_193q <= av_readdata(9);
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_read_latency_shift_reg_0_209q <= (uav_read AND (wire_w_lg_av_waitrequest165w(0) AND wire_nO_w166w(0)));
		END IF;
	END PROCESS;
	PROCESS (clk, reset)
	BEGIN
		IF (reset = '1') THEN
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_waitrequest_reset_override_170q <= '1';
		ELSIF (clk = '1' AND clk'event) THEN
				nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_waitrequest_reset_override_170q <= s_wire_gnd;
		END IF;
		if (now = 0 ns) then
			nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_waitrequest_reset_override_170q <= '1' after 1 ps;
		end if;
	END PROCESS;
	wire_nO_w166w(0) <= NOT nios1_jtag_uart_avalon_jtag_slave_translator_altera_merlin_slave_translator_jtag_uart_avalon_jtag_slave_translator_waitrequest_reset_override_170q;

 END RTL; --Nios1_jtag_uart_avalon_jtag_slave_translator
--synopsys translate_on
--VALID FILE
